name: thenafter_dart
description: Parses the BNF .grm file and produces the first and follow sets.
  It can be used also to generate first and follow sets in a set of different languages.
version: 0.5.0
repository: https://github.com/Jictyvoo/thenafter-dart

environment:
  sdk: '>=2.13.1 <3.0.0'

dependencies:
  args: ^2.1.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
