name: thenafter_dart
description: Produces synthatic functions from a grammar
version: 0.0.1
author: João Victor Oliveira Couto

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  args: ^2.1.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
